---

  logging:
    level:
      org.springframework: INFO

  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost/cards
      username: postgres
      password: postgres
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
    jackson:
      serialization:
        indentOutput: true